[python]
# Modules to be brought up by simply running the python processes async
# Leave this empty if no blocks should be started like this
modules_root = '../'                                                            # path to the root if the modules

# -------------------- cVEP Speller ---------------------------------------
[python.modules.dp-seller]
    type = 'io_data'
    port = 8081
    ip = '127.0.0.1'

# -------------------- Mockup Streamer ---------------------------------------
[python.modules.dp-mockup-streamer]
    type = 'io_data'
    port = 8082
    ip = '127.0.0.1'
[python.modules.dp-mockup-streamer.kwargs]
    lsl_out_stream_name = 'mockup_EEG_stream'
    # random_data = true --> use the start random button!




[macros]

[macros.start_streaming]
    name = 'START_STREAMING'
    description = 'start streaming'
[macros.start_streaming.default_json]
    stream_name = 'mockup_stream'
    date_root = '../'
[macros.start_streaming.cmds]
    # [<target_module>, <PCOMM>, <kwarg_name1 (optional)>, <kwarg_name2 (optional)>]
    com1 = ['dp-mockup-streamer', 'START']
    # com2 = ['dareplane_spoc_recording', 'SET_SAVE_PATH', 'rec_dir=data_root']

[macros.stop_streaming]
    name = 'STOP_STREAMING'
    description = 'start streaming'
[macros.stop_streaming.cmds]
    # [<target_module>, <PCOMM>, <kwarg_name1 (optional)>, <kwarg_name2 (optional)>]
    com1 = ['dp-mockup-streamer', 'STOP']
    # com2 = ['dareplane_spoc_recording', 'SET_SAVE_PATH', 'rec_dir=data_root']
